server:
  port: 8081

spring:
  application:
    name: authservice

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: ${JWT_SECRET:my-32-character-ultra-secure-and-ultra-long-secret}
    issuer: unityhospital
    expiryMinutes: 60